pull_request:
  base: 10
  per_line: 0.1
  max_size_bonus: 50
  per_file: 2
  
  multipliers:
    bug: 1.5
    feature: 1.3
    documentation: 1.2
    test: 1.1
    chore: 0.8
  
  caps:
    min_points: 1
    max_points: 100
  
  first_contribution_bonus: 20

code_review:
  base: 5
  detailed_feedback_bonus: 5
  approved: 0
  changes_requested: 3
  
issue:
  created: 2
  closed: 5
  well_documented_bonus: 3
